//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IORPromoteTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public short emp_number { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string status { get; set; }
        public Nullable<bool> parttime { get; set; }
        public string emp_nickname { get; set; }
        public string emp_title { get; set; }
        public string emp_sex { get; set; }
        public string nwuser { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string report_to { get; set; }
        public Nullable<short> reporttoID { get; set; }
        public string department { get; set; }
        public string emp_group { get; set; }
        public string emp_unit { get; set; }
        public string location { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string phone_num { get; set; }
        public string mobile_num { get; set; }
        public bool IsManager { get; set; }
        public bool IsEmployed { get; set; }
        public Nullable<double> LastYearVacationHour { get; set; }
        public Nullable<int> compday { get; set; }
        public Nullable<double> LastYearSickHour { get; set; }
        public byte[] picture { get; set; }
        public Nullable<System.DateTime> original_hiredate { get; set; }
        public string primary_location { get; set; }
        public Nullable<bool> consultant { get; set; }
    }
}
