//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IORPromoteTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IORRequest
    {
        public int Id { get; set; }
        public int IOR_ID { get; set; }
        public string Kanban_ID { get; set; }
        public string Submitter { get; set; }
        public string Department { get; set; }
        public string Request_Title { get; set; }
        public string Request_Type { get; set; }
        public string Request_System { get; set; }
        public string Request_Category { get; set; }
        public string Request_Priority { get; set; }
        public string Request_Status { get; set; }
        private System.DateTime _Request_File_Date; public System.DateTime Request_File_Date { get { return _Request_File_Date; } set { _Request_File_Date = DateKindHelper.DefaultToUtc(value); }}
        private System.DateTime _Request_Approved_Date; public System.DateTime Request_Approved_Date { get { return _Request_Approved_Date; } set { _Request_Approved_Date = DateKindHelper.DefaultToUtc(value); }}
        private Nullable<System.DateTime> _Request_UAT_Date; public Nullable<System.DateTime> Request_UAT_Date { get { return _Request_UAT_Date; } set { _Request_UAT_Date = DateKindHelper.DefaultToUtc(value); }}
        private Nullable<System.DateTime> _Request_End_Date; public Nullable<System.DateTime> Request_End_Date { get { return _Request_End_Date; } set { _Request_End_Date = DateKindHelper.DefaultToUtc(value); }}
    }
}
