//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IORPromoteTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IORSetting
    {
        public int Id { get; set; }
        public string BoardId { get; set; }
        public string TempPath { get; set; }
        public string PromoteLane { get; set; }
        public bool LogInfo { get; set; }
        public bool LogDetails { get; set; }
        public int PromoteFrequency { get; set; }
        public string Environment { get; set; }
    }
}
