//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IORPromoteTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoteUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public int Frequency { get; set; }
        private Nullable<System.DateTime> _LastPromote; public Nullable<System.DateTime> LastPromote { get { return _LastPromote; } set { _LastPromote = DateKindHelper.DefaultToUtc(value); }}
    }
}
