//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IORPromoteTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestPromoteEntities : DbContext
    {
        public TestPromoteEntities()
            : base("name=TestPromoteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IORSetting> IORSettings { get; set; }
        public DbSet<PromoteRecord> PromoteRecords { get; set; }
        public DbSet<PromoteUser> PromoteUsers { get; set; }
        public DbSet<PromoteFrequency> PromoteFrequencies { get; set; }
        public DbSet<IORRequest> IORRequests { get; set; }
    }
}
